route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: {{ ALERTS_EMAIL }}
    from: {{ ALERTS_EMAIL }}
    smarthost: smtp.gmail.com:587
    auth_username: {{ ALERTS_EMAIL }}
    auth_identity: {{ ALERTS_EMAIL }}
    auth_password: {{ ALERTS_PASSWORD }}
