groups:
  - name: Down
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 3m
      labels:
        severity: 'critical'
      annotations:
        summary: "Instance is down"
        description: "job has been down for more than 3 minutes. View in alertmanager {% for IP in groups['monitor'] %}http://{{ IP }}:9093{% endfor %}"
