---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "set database environment variables"
  shell: |
    export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST')}}"
    export TYPEORM_PORT=5432
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME')}}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE')}}"
    export TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    export TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
