
# - name: Copy server archive
#   ansible.builtin.copy:
#     src: files/server.tar.gz
#     dest: ~/server.tar.gz

- name: Unarchive server files
  ansible.builtin.unarchive:
    src: files/server.tar.gz
    dest: ~/

# - name: Executing node
#   shell: |
#     pm2 start ~/web/index.js -f
