- name: "Add Prometheus User"
  user:
    name: prometheus
    create_home: no

- name: "install prometheus."
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move prometheus binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: '0777'

- name: "move promtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    remote_src: yes
    mode: '0777'

- name: "move consoles directory to /etc/prometheus."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/consoles
    dest: /etc/prometheus
    remote_src: yes
    mode: '0777'

- name: "move console_libraries directory to /etc/prometheus."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/console_libraries
    dest: /etc/prometheus
    remote_src: yes
    mode: '0777'

- name: "add /etc/prometheus/prometheus.yml"
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: "add systemd prometheus configuration."
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/

## Change ownership of prometheus directories to the prometheus user

- name: "sudo chown prometheus:prometheus /etc/prometheus"
  become: true
  file:
    path: "/etc/prometheus"
    owner: prometheus
    group: prometheus

- name: "sudo chown prometheus:prometheus /usr/local/bin/prometheus"
  become: true
  file:
    path: "/usr/local/bin/prometheus"
    owner: prometheus
    group: prometheus

- name: "sudo chown prometheus:prometheus /usr/local/bin/promtool"
  become: true
  file:
    path: "/usr/local/bin/promtool"
    owner: prometheus
    group: prometheus

- name: "sudo chown -R prometheus:prometheus /etc/prometheus/consoles"
  become: true
  file:
    path: "/etc/prometheus/consoles"
    owner: prometheus
    group: prometheus
    recurse: yes

- name: "sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries"
  become: true
  file:
    path: "/etc/prometheus/console_libraries"
    owner: prometheus
    group: prometheus
    recurse: yes

- name: "sudo chown -R prometheus:prometheus /var/lib/prometheus"
  become: true
  file:
    path: "/var/lib/prometheus"
    owner: prometheus
    group: prometheus
    recurse: yes

- name: "enable prometheus service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus
    enabled: yes

# TODO: is this accounted for?

# sudo systemctl daemon-reload
# sudo systemctl enable prometheus
# sudo systemctl start prometheus.service
