## Install prometheus

- name: "Add Prometheus User"
  user:
    name: prometheus
    create_home: no

- name: "install prometheus."
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move prometheus binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: '0777'
    owner: prometheus
    group: prometheus

- name: "move promtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    remote_src: yes
    mode: '0777'
    owner: prometheus
    group: prometheus

- name: "move consoles directory to /etc/prometheus."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/consoles
    dest: /etc/prometheus
    remote_src: yes
    owner: prometheus
    group: prometheus

- name: "move console_libraries directory to /etc/prometheus."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/console_libraries
    dest: /etc/prometheus
    remote_src: yes
    owner: prometheus
    group: prometheus

- name: "add /etc/prometheus/prometheus.yml"
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    group: prometheus
    owner: prometheus

- name: "add /etc/prometheus/rules.yml"
  become: true
  copy:
    src: rules.yml
    dest: /etc/prometheus/rules.yml
    group: prometheus
    owner: prometheus

- name: "creates /var/lib/prometheus directory"
  become: true
  file:
    path: /var/lib/prometheus
    state: directory
    group: prometheus
    owner: prometheus

- name: "add systemd prometheus configuration."
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
    group: prometheus
    owner: prometheus

## Install alert manager

- name: "install alertmanager"
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "cp alertmanager-0.21.0.linux-amd64/alertmanager /usr/local/bin"
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/alertmanager
    dest: /usr/local/bin
    remote_src: yes
    mode: '0777'

- name: "cp alertmanager-0.21.0.linux-amd64/amtool /usr/local/bin/"
  become: true
  copy:
    src: /tmp/alertmanager-0.21.0.linux-amd64/amtool
    dest: /usr/local/bin
    remote_src: yes
    mode: '0777'

- name: "creates /var/lib/alertmanager directory"
  become: true
  file:
    path: /var/lib/alertmanager
    state: directory

- name: "add /etc/prometheus/alertmanager.yml"
  become: true
  template:
    src: alertmanager.yml
    dest: /etc/prometheus/alertmanager.yml

- name: "add /etc/systemd/system/alertmanager.service"
  become: true
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

## enable systemd services

- name: "enable prometheus service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus
    enabled: yes

- name: "enable alert manager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes
